 "use client";
import {useState} from "react";
const edges=[["Riyadh-Edge-01","Online","Riyadh","10.10.1.11"],["Riyadh-Edge-02","Online","Riyadh","10.10.1.12"],["Jeddah-Edge-01","Warning","Jeddah","10.20.1.11"]];
const trunks=[["Hospital-SIP-01","Healthy","sip01.provider.local","5060","UDP"],["Emergency-Trunk","Warning","emergency.provider.local","5061","TCP"],["DR-SIP-01","Offline","dr.provider.local","5060","UDP"]];
const sites=[["Riyadh Main Site","Healthy","2 Edges","2 Trunks"],["Jeddah Site","Warning","1 Edge","1 Trunk"],["Dammam Site","Healthy","1 Edge","1 Trunk"]];
function Badge({s}:{s:string}){return <span className={"badge "+s.toLowerCase()}>{s}</span>}
export default function Home(){
 const [connected,setConnected]=useState(false); const [tab,setTab]=useState("Overview"); const [target,setTarget]=useState("10.10.1.11"); const [result,setResult]=useState<any>(null);
 async function diagnose(){setResult({loading:true}); const r=await fetch("/api/diagnostics",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({target})}); setResult(await r.json())}
 if(!connected) return <main className="login"><div className="login-card"><div className="logo">G</div><div className="eyebrow">GENESYS TELEPHONY & NETWORK TOOLKIT</div><h1>Connect Genesys Cloud</h1><p>Connect your organization to manage Sites, Edges, Trunks and telephony diagnostics from one workspace.</p><label>Client ID<input id="clientId" placeholder="Genesys Cloud Client ID"/></label><label>Client Secret<input type="password" placeholder="Genesys Cloud Client Secret"/></label><label>Region<select><option>Middle East (UAE)</option><option>Americas (US East)</option><option>Europe (Ireland)</option><option>Asia Pacific (Sydney)</option></select></label><button className="primary wide" onClick={()=>setConnected(true)}>Connect</button><div className="security">Secure OAuth will be wired to the server-side callback in the next integration step. Never commit Client Secrets to GitHub.</div></div></main>;
 return <div className="shell"><aside><div className="brand"><span className="logo small">G</span><div><b>Genesys Toolkit</b><small>Telephony & Network</small></div></div>{["Overview","Sites","Edges","Trunks","Edge Groups","Number Plans","Outbound Routes","Diagnostics","Backup","Audit Log"].map(x=><button className={tab===x?"nav active":"nav"} onClick={()=>setTab(x)} key={x}>{x}</button>)}<div className="side-status"><span className="green-dot"/> Connected<br/><b>Hospital Production</b></div></aside>
 <section className="main"><header><span>Telephony Toolkit / <b>{tab}</b></span><span className="connected">● Connected · Demo API</span></header><div className="content">
 {tab==="Overview"&&<><div className="hero"><div><h1>Telephony & Network Overview</h1><p>Monitor and troubleshoot Genesys Cloud telephony from one place.</p></div><button className="primary" onClick={()=>setTab("Diagnostics")}>Run Diagnostics</button></div><div className="stats"><Stat n="3" t="Sites" s="2 healthy · 1 warning"/><Stat n="3" t="Edges" s="2 online · 1 warning"/><Stat n="3" t="External Trunks" s="1 warning · 1 offline"/><Stat n="2" t="Active Issues" s="Needs attention"/></div><div className="grid"><Panel title="System Health"><Health n="Sites" s="Healthy"/><Health n="Edges" s="Warning"/><Health n="Trunks" s="Warning"/><Health n="Routing" s="Healthy"/></Panel><Panel title="Quick Actions"><div className="quick">{["Ping Device","Test SIP Port","Site Health Check","Export Config"].map(x=><button key={x} onClick={()=>setTab("Diagnostics")}>{x}</button>)}</div></Panel></div></>}
 {tab==="Sites"&&<><Title t="Sites" d="Sites, attached Edges, Trunks and health."/><Table h={["Site","Status","Edges","Trunks"]} rows={sites}/></>}
 {tab==="Edges"&&<><Title t="Edges" d="Edge inventory and connectivity."/><Table h={["Name","Status","Site","IP"]} rows={edges}/></>}
 {tab==="Trunks"&&<><Title t="External Trunks" d="SIP trunks, transport, ports and health."/><Table h={["Name","Status","Host","Port","Transport"]} rows={trunks}/></>}
 {tab==="Diagnostics"&&<><Title t="Troubleshooting Center" d="Run network checks against an Edge, Trunk or Site target."/><div className="diag"><label>Target IP / Host<input value={target} onChange={e=>setTarget(e.target.value)}/></label><div className="checks"><span>✓ Ping</span><span>✓ TCP 5060</span><span>✓ TCP 5061</span><span>✓ TCP 443</span><span>✓ DNS</span><span>✓ SIP</span></div><button className="primary" onClick={diagnose}>Run Diagnostics</button>{result&&<div className="result">{result.loading?"Running diagnostics…":<><h3>Diagnostic Result</h3><Health n="Target" s={result.target}/><Health n="Ping" s={result.ping}/><Health n="TCP 5060" s={result.tcp5060}/><Health n="TCP 5061" s={result.tcp5061}/><Health n="TCP 443" s={result.tcp443}/><Health n="DNS" s={result.dns}/><p>{result.note}</p></>}</div>}</div></>}
 {["Edge Groups","Number Plans","Outbound Routes","Backup","Audit Log"].includes(tab)&&<><Title t={tab} d="Module ready for the live Genesys Cloud API integration."/><div className="empty">This module is included in the architecture and will be connected to live Genesys data after OAuth is configured.</div></>}
 </div></section></div>
}
function Stat({n,t,s}:{n:string,t:string,s:string}){return <div className="stat"><small>{t}</small><strong>{n}</strong><span>{s}</span></div>}
function Panel({title,children}:{title:string,children:any}){return <div className="panel"><h3>{title}</h3><div className="panel-body">{children}</div></div>}
function Health({n,s}:{n:string,s:string}){return <div className="health"><b>{n}</b><Badge s={s}/></div>}
function Title({t,d}:{t:string,d:string}){return <div className="hero"><div><h1>{t}</h1><p>{d}</p></div></div>}
function Table({h,rows}:{h:string[],rows:string[][]}){return <div className="panel tablewrap"><table><thead><tr>{h.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{j===1?<Badge s={x}/>:x}</td>)}</tr>)}</tbody></table></div>}